### ISSUE TITLE
node-webkit-builder deprecated

### ISSUE THREAD

**Issue by simonbcn** [leftstick/gulp-nw-builder#1]
When I install the dependencies for  [Aluxian/WhatsApp-Desktop](https://github.com/Aluxian/WhatsApp-Desktop) it shows this warning:

```
npm WARN deprecated node-webkit-builder@1.0.13: WARNING: This module has been renamed to nw-builder. Install using nw-builder instead, node-webkit-builder will no longer be updated.
```

**Comment by leftstick** [comment]
Thanks for remindin. It's Fixed.

**Comment by leftstick** [comment]
But actually [WhatApp](https://github.com/Aluxian/WhatsApp-Desktop) are using a fork of this repo. You have to ask @Aluxian fetching the latest updates ^^

**Comment by simonbcn** [comment]
I don't understand. If I download the git version of `Aluxian/WhatsApp-Desktop` and I execute `npm install`, doesn't it download this last version?

**Comment by leftstick** [comment]
I believe so, since @Aluxian fork my repo at a specific point, and publish it to the npm registry. Which means `npm` stored that version. Even i've updated my repo, you still won't get the latest one until @Aluxian fetch my updates to his fork and publish it to `npm`.

**Comment by simonbcn** [comment]
ok, thanks. I've reported this error in @Aluxian repo.
